import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // All colors reference CSS vars — dark mode works by swapping vars under .dark
        'surface':                   'var(--color-surface)',
        'surface-dim':               'var(--color-surface-dim)',
        'surface-bright':            'var(--color-surface-bright)',
        'surface-container-lowest':  'var(--color-surface-container-lowest)',
        'surface-container-low':     'var(--color-surface-container-low)',
        'surface-container':         'var(--color-surface-container)',
        'surface-container-high':    'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-surface':                'var(--color-on-surface)',
        'on-surface-variant':        'var(--color-on-surface-variant)',
        'inverse-surface':           'var(--color-inverse-surface)',
        'inverse-on-surface':        'var(--color-inverse-on-surface)',
        'primary':                   'var(--color-primary)',
        'on-primary':                'var(--color-on-primary)',
        'primary-container':         'var(--color-primary-container)',
        'on-primary-container':      'var(--color-on-primary-container)',
        'inverse-primary':           'var(--color-inverse-primary)',
        'secondary':                 'var(--color-secondary)',
        'on-secondary':              'var(--color-on-secondary)',
        'secondary-container':       'var(--color-secondary-container)',
        'on-secondary-container':    'var(--color-on-secondary-container)',
        'tertiary':                  'var(--color-tertiary)',
        'on-tertiary':               'var(--color-on-tertiary)',
        'tertiary-container':        'var(--color-tertiary-container)',
        'on-tertiary-container':     'var(--color-on-tertiary-container)',
        'error':                     'var(--color-error)',
        'on-error':                  'var(--color-on-error)',
        'error-container':           'var(--color-error-container)',
        'on-error-container':        'var(--color-on-error-container)',
        'outline':                   'var(--color-outline)',
        'outline-variant':           'var(--color-outline-variant)',
        'background':                'var(--color-background)',
        'on-background':             'var(--color-on-background)',
      },
      fontFamily: {
        sans:  ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        mono:  ['var(--font-jetbrains)', 'JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg':  ['3.5rem',  { lineHeight: '1.1',  letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-md':  ['2.8rem',  { lineHeight: '1.15', letterSpacing: '-0.015em', fontWeight: '700' }],
        'display-sm':  ['2.25rem', { lineHeight: '1.2',  letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['2rem',    { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['1.75rem', { lineHeight: '1.3',  fontWeight: '600' }],
        'headline-sm': ['1.5rem',  { lineHeight: '1.35', fontWeight: '600' }],
        'title-lg':    ['1.25rem', { lineHeight: '1.4',  fontWeight: '600' }],
        'title-md':    ['1.125rem',{ lineHeight: '1.45', fontWeight: '500' }],
        'title-sm':    ['1rem',    { lineHeight: '1.5',  fontWeight: '500' }],
        'body-lg':     ['1rem',    { lineHeight: '1.6',  fontWeight: '400' }],
        'body-md':     ['0.875rem',{ lineHeight: '1.6',  fontWeight: '400' }],
        'body-sm':     ['0.75rem', { lineHeight: '1.5',  fontWeight: '400' }],
        'label-lg':    ['0.875rem',{ lineHeight: '1.4',  letterSpacing: '0.02em', fontWeight: '600' }],
        'label-md':    ['0.75rem', { lineHeight: '1.4',  letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm':    ['0.6875rem',{lineHeight: '1.4',  letterSpacing: '0.08em', fontWeight: '600' }],
      },
      spacing: {
        'xs':  '0.25rem',
        'sm':  '0.5rem',
        'md':  '1rem',
        'lg':  '1.5rem',
        'xl':  '2rem',
        '2xl': '3rem',
        '3xl': '4rem',
      },
      borderRadius: {
        'xs': '0.25rem',
        'sm': '0.375rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        '2xl':'1.25rem',
        '3xl':'1.5rem',
      },
      boxShadow: {
        'card':   '0 1px 3px rgba(0,0,0,0.1), 0 1px 2px rgba(0,0,0,0.06)',
        'card-md':'0 4px 6px rgba(0,0,0,0.07), 0 2px 4px rgba(0,0,0,0.05)',
        'card-lg':'0 10px 15px rgba(0,0,0,0.1), 0 4px 6px rgba(0,0,0,0.05)',
        'glow':   '0 0 24px rgba(0,56,209,0.35)',
        'glow-sm':'0 0 12px rgba(0,56,209,0.25)',
      },
      animation: {
        'fade-in':     'fadeIn 0.3s ease-out',
        'slide-up':    'slideUp 0.3s ease-out',
        'slide-down':  'slideDown 0.3s ease-out',
        'pulse-slow':  'pulse 3s cubic-bezier(0.4,0,0.6,1) infinite',
        'spin-slow':   'spin 8s linear infinite',
        'float':       'float 6s ease-in-out infinite',
        'glow-pulse':  'glowPulse 2s ease-in-out infinite',
        'shimmer':     'shimmer 2s infinite',
      },
      keyframes: {
        fadeIn:    { from: { opacity: '0' },                    to: { opacity: '1' } },
        slideUp:   { from: { transform: 'translateY(8px)', opacity: '0' }, to: { transform: 'translateY(0)', opacity: '1' } },
        slideDown: { from: { transform: 'translateY(-8px)', opacity: '0' }, to: { transform: 'translateY(0)', opacity: '1' } },
        float:     { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-8px)' } },
        glowPulse: { '0%,100%': { opacity: '1', boxShadow: '0 0 12px rgba(0,56,209,0.25)' }, '50%': { opacity: '0.7', boxShadow: '0 0 24px rgba(0,56,209,0.45)' } },
        shimmer:   { from: { backgroundPosition: '200% center' }, to: { backgroundPosition: '-200% center' } },
      },
      backdropBlur: { xs: '2px', sm: '4px', md: '8px', lg: '12px', xl: '16px' },
    },
  },
  plugins: [],
}

export default config
