import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
    './types/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface':                    '#f9f9ff',
        'surface-dim':                '#d3daea',
        'surface-bright':             '#f9f9ff',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f0f3ff',
        'surface-container':          '#e7eefe',
        'surface-container-high':     '#e2e8f8',
        'surface-container-highest':  '#dce2f3',
        'surface-tint':               '#0646f8',
        'on-surface':                 '#151c27',
        'on-surface-variant':         '#434656',
        'inverse-surface':            '#2a313d',
        'inverse-on-surface':         '#ebf1ff',
        'primary':                    '#0038d1',
        'on-primary':                 '#ffffff',
        'primary-container':          '#1b4fff',
        'on-primary-container':       '#dfe2ff',
        'inverse-primary':            '#b9c3ff',
        'primary-fixed':              '#dde1ff',
        'primary-fixed-dim':          '#b9c3ff',
        'on-primary-fixed':           '#001257',
        'on-primary-fixed-variant':   '#0033c1',
        'secondary':                  '#575e72',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#dbe2fa',
        'on-secondary-container':     '#5d6478',
        'tertiary':                   '#3636c5',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#5052dd',
        'on-tertiary-container':      '#e2e0ff',
        'outline':                    '#747688',
        'outline-variant':            '#c4c5d9',
        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'on-error-container':         '#93000a',
        'background':                 '#f9f9ff',
        'on-background':              '#151c27',
      },
      spacing: {
        'xs':              '4px',
        'base':            '8px',
        'sm':              '12px',
        'md':              '24px',
        'lg':              '48px',
        'xl':              '80px',
        'gutter-mobile':   '16px',
        'gutter-desktop':  '24px',
        'margin-mobile':   '20px',
        'margin-desktop':  '64px',
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'sm':      '0.25rem',
        'md':      '0.75rem',
        'lg':      '1rem',
        'xl':      '1.5rem',
        'full':    '9999px',
      },
      fontFamily: {
        'sans':  ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        'mono':  ['var(--font-jetbrains)', 'JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        'headline-xl':        ['48px',  { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl-mobile': ['32px',  { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg':        ['32px',  { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md':        ['24px',  { lineHeight: '32px', fontWeight: '600' }],
        'body-lg':            ['18px',  { lineHeight: '28px', fontWeight: '400' }],
        'body-md':            ['16px',  { lineHeight: '24px', fontWeight: '400' }],
        'label-md':           ['14px',  { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm':           ['12px',  { lineHeight: '16px', fontWeight: '500' }],
      },
      boxShadow: {
        'card':       '0 4px 20px rgba(0, 56, 209, 0.05)',
        'card-hover': '0 8px 32px rgba(0, 56, 209, 0.12)',
        'glow':       '0 0 24px rgba(0, 56, 209, 0.35)',
        'glow-sm':    '0 0 12px rgba(0, 56, 209, 0.25)',
      },
    },
  },
  plugins: [],
}

export default config
